//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BrentUniversity.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Student 
    {
        public Student()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
        
        public int Id { get; set; }
        
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is required.")]
        public string LastName { get; set; }
        
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required.")]
        public string FirstName { get; set; }

        [Display(Name = "Enroll Date")]
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Enrollment Date is required.")]
        public DateTime EnrollmentDate { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
